### ISSUE TITLE
Timestamp

### ISSUE THREAD

**Issue by sramchandra89** [aws-samples/amazon-ec2-gitlab-runner#3]
Timestamp parameter is missing

**Comment by sylvia-qi-swi** [comment]
Hi @sramchandra89, apologies for the delayed response. I thought I responded before but i might not have hit the comment button. The value for the Timestamp parameter is auto-generated in the deploy-runner.sh script: https://github.com/aws-samples/amazon-ec2-gitlab-runner/blob/266ecca221d3a5f4a271184ce20471b1be190f9b/deploy-runner.sh#L178. 

It is designed this way so users don't have to be concered about it, and it guarantees uniqueness of the value.
