### ISSUE TITLE
RunnerAutoScalingGroup is failed

### ISSUE THREAD

**Issue by asannikov** [aws-samples/amazon-ec2-gitlab-runner#4]
There is an error on running:

`./deploy-runner.sh sample-runner.properties eu-central-1 profilename amazon-ec2-gitlab-runner-demo`

error:

```
amazon-ec2-gitlab-runner-demo | ROLLBACK_IN_PROGRESS | The following resource(s) failed to create: [RunnerAutoScalingGroup]. Rollback requested by user.
-- | -- | -- | --
RunnerAutoScalingGroup | CREATE_FAILED | Received 0 SUCCESS signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement
-- | -- | -- | --
RunnerAutoScalingGroup | UPDATE_IN_PROGRESS | Failed to receive 1 resource signal(s) for the current batch. Each resource signal timeout is counted as a FAILURE.

```
at the same time, I'm seeing successfully created and running EC2 instance. VPC was created from template https://tomgregory-cloudformation-examples.s3-eu-west-1.amazonaws.com/default-vpc.yml

**Comment by qisylvia** [comment]
Hi @asannikov, 
Thanks for reaching out. Please refer to answers in this issue: https://github.com/aws-samples/amazon-ec2-gitlab-runner/issues/1. Does this help?
