### ISSUE TITLE
Error parsing parameter '--template-body'

### ISSUE THREAD

**Issue by JohnBelliveauNB** [aws-samples/amazon-ec2-gitlab-runner#5]
Fails right out of the gate!

```
Stack does not exist, creating it...

Error parsing parameter '--template-body': Unable to load paramfile file://gitlab-runner.yaml: [Errno 2] No such file or directory: 'gitlab-runner.yaml'
Stack creation failed
```
gitlab-runner.yaml exists with permissions 644 in the directory where the script is called from

**Comment by sylvia-qi-swi** [comment]
Hello @JohnBelliveauNB. I can recreate this error when npm is not installed in my system (Note npm is one of the prerequisites). If you are running MacOS you can install it using "brew install npm". 

This is my output when npm is not installed:
bcd0741227d7:amazon-ec2-gitlab-runner sylviqi$ ./deploy-runner.sh sample-runner.properties us-east-1 default gitlab-runner-demo
Deploying Gitlab runner in region: us-east-1, using AWS profile: default
CloudFormation stack name: gitlab-runner-demo
OSX
  adding: gitlab-runner-lifecycle-hook.py (deflated 73%)
upload: ./gitlab-runner-demo-lifecycle-hook-20220719095948.zip to s3://sylviqi-test/gitlab-runner-demo/gitlab-runner-demo-lifecycle-hook-20220719095948.zip
.**/deploy-runner.sh: line 97: npm: command not found
./deploy-runner.sh: line 98: npm: command not found
./deploy-runner.sh: line 99: cd: bin: No such file or directory**
OSX
  adding: package.json (deflated 49%)
  adding: src/ (stored 0%)
  adding: src/lib/ (stored 0%)
  adding: src/lib/adjustScaling.ts (deflated 57%)
  adding: src/lib/gatherMetrics.ts (deflated 71%)
  adding: src/lib/asgInfo.ts (deflated 73%)
  adding: src/lib/publishMetrics.ts (deflated 67%)
  adding: src/lib/utils.ts (deflated 62%)
  adding: src/lib/config.ts (deflated 75%)
  adding: src/index.ts (deflated 56%)
  adding: tsconfig.json (deflated 53%)
upload: ./gitlab-runner-demo-runner-monitor-20220719095948.zip to s3://sylviqi-test/gitlab-runner-demo/gitlab-runner-demo-runner-monitor-20220719095948.zip
Checking if stack already exists...
An error occurred (ValidationError) when calling the DescribeStacks operation: Stack with id gitlab-runner-demo does not exist
Stack does not exist, creating it...

Error parsing parameter '--template-body': Unable to load paramfile file:///gitlab-runner.yaml: [Errno 2] No such file or directory: '/gitlab-runner.yaml'
Stack creation failed

After I installed npm this error disappeared. 

If you are still getting the same issue after npm is installed, please update the ticket with the entire output of the deploy-runner.sh command. Thanks.

**Comment by JohnBelliveauNB** [comment]
Thank you @sylvia-qi-swi for leading me to discover that my npm was not installed correctly, as I was not getting the **npm: command not found** errors in my output!
