### ISSUE TITLE
The runtime parameter of python3.6 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (python3.9) while creating or updating functions

### ISSUE THREAD

**Issue by boy51** [aws-samples/amazon-ec2-gitlab-runner#7]
Getting this error in CF

```
Resource handler returned message: "The runtime parameter of python3.6 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (python3.9) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: [...])" (RequestToken: [...], HandlerErrorCode: InvalidRequest)
```

**Comment by qisylvia** [comment]
Hi @boy51, support for AWS Lambda python3.6 has ended. https://aws.amazon.com/blogs/developer/python-support-policy-updates-for-aws-sdks-and-tools/. You will need to upgrade python runtime to 3.9 here: https://github.com/aws-samples/amazon-ec2-gitlab-runner/blob/266ecca221d3a5f4a271184ce20471b1be190f9b/gitlab-runner.yaml#L430.

**Comment by boy51** [comment]
Yes, I also made a PR for this :)

**Comment by qisylvia** [comment]
Hi @boy51, the PR has been merged. Thanks!
