### ISSUE TITLE
How to configure runners to run untagged jobs

### ISSUE THREAD

**Issue by boy51** [aws-samples/amazon-ec2-gitlab-runner#9]
Hi,

thanks for the great guide.

I am wondering how to better configure the runners how I want them. I want all my runners to be able to run untagged jobs and unprotected branches. In the config there is `RunnerEnvironment` which maps values to `isLOCKED` and `ACCESS` so I know how to change those. But where can I set the option from gitlab ui to allow runner to run untagged jobs?

And just a side note, there is no mention of which AMI image should be used in the entire article. It took me a while to figure out it was amazon linux ami.

Thanks

**Comment by qisylvia** [comment]
Hi @boy51, please check this link for info on how to configure runners to run untag jobs. https://docs.gitlab.com/ee/ci/runners/configure_runners.html#set-a-runner-to-run-untagged-jobs

**Comment by boy51** [comment]
Thanks for the link, I've managed to do this by including `--runUntagged="true"` option in `runner.yaml`.
